### ISSUE TITLE
Scss encapsulation within project

### ISSUE THREAD

**Issue by wdesgardin** [PichotM/pPhone2#21]
In this project we're creating a scss file for each component (or group of related components).
But, the rules defined in these files are not component-scoped, so they are applied everywhere.

One solution is to wrap every rules, like I've done here : 

```scss
#call-container {
    h1 {
        font-weight: normal !important;
        font-size: 22px;
        text-align: center;
        margin-bottom: 0px;
    }

    h2 {
        font-weight: normal !important;
        font-size: 12px;
        text-align: center;
        margin: 4px;
    }

    h3 {
        font-weight: normal !important;
        font-size: 10px;
        text-align: center;
        margin: 5px 0;
    }
}
```

But, I think it would be better to use somethink like this : https://github.com/gaoxiaoliangz/react-scoped-css
